version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  labels: []
  reviewers: [Katsute]
  schedule:
    interval: daily
    time: '06:00'
    timezone: US/Eastern
  open-pull-requests-limit: 99

- package-ecosystem: maven
  directory: /
  labels: []
  reviewers: [Katsute]
  schedule:
    interval: daily
    time: '06:00'
    timezone: US/Eastern
  open-pull-requests-limit: 99