name: Java CI
on:
  push: {}
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  java_ci:
    name: Java CI
    runs-on: windows-2019
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v3

      - name: ☕ Install Java
        uses: actions/setup-java@v3
        with:
          architecture: x64
          cache: maven
          distribution: temurin
          java-version: 11

      - name: ✔ Test with Maven
        run: mvn test -fae --no-transfer-progress