name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

permissions: read-all

jobs:
  java_ci:
    name: Java CI
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          architecture: x64
          cache: maven
          distribution: temurin
          java-version: 21

      - name: Test with Maven
        run: mvn test -fae --no-transfer-progress